/**
 * Values that must be present-but-empty so Next.js cannot restore them from
 * `.env.local` when Playwright starts the application server.
 */
export const TEST_SERVER_BLOCKED_ENV_NAMES = Object.freeze([
  "NEXT_PUBLIC_PRIVY_APP_ID",
  "PRIVY_APP_ID",
  "PRIVY_APP_SECRET",
  "PRIVY_VERIFICATION_KEY",
  "PRIVY_AUTHORIZATION_PRIVATE_KEY",
  "PRIVY_KEY_QUORUM_ID",
  "PRIVY_POLYMARKET_POLICY_ID",
  "PRIVY_DFLOW_POLICY_ID",
  "PRIVY_OPINION_POLICY_ID",
  "PRIVY_PREDICT_FUN_POLICY_ID",
  "PRIVY_LIMITLESS_POLICY_ID",
  "PRIVY_SXBET_POLICY_ID",
  "PRIVY_HYDROMANCER_POLICY_ID",
  "BLOB_READ_WRITE_TOKEN",
  "CRON_SECRET",
  "SUPABASE_WEB_DATABASE_URL",
  "SUPABASE_MARKET_DATABASE_URL",
  "SUPABASE_EXECUTION_DATABASE_URL",
  "SUPABASE_MIGRATION_DATABASE_URL",
  "TXBET_ENVELOPE_ACTIVE_KEY_ID",
  "TXBET_ENVELOPE_KEYRING_JSON",
  "TXLINE_BASE_URL",
  "TXLINE_API_TOKEN",
  "TXLINE_WORLD_CUP_COMPETITION_IDS",
  "TXLINE_FIXTURE_ID",
  "ASSET_VALUE_POLICIES_JSON",
  "POLYMARKET_CLOB_URL",
  "POLYMARKET_MARKET_WS_URL",
  "POLYMARKET_USER_WS_URL",
  "POLYMARKET_GAMMA_URL",
  "POLYMARKET_WORLD_CUP_SHADOW_REVIEW_JSON",
  "POLYMARKET_RELAYER_URL",
  "POLYMARKET_CHAIN_ID",
  "POLYMARKET_COLLATERAL_ADDRESS",
  "POLYMARKET_CTF_ADDRESS",
  "POLYMARKET_EXCHANGE_ALLOWLIST",
  "POLYMARKET_RELAYER_API_KEY",
  "POLYMARKET_RELAYER_API_KEY_ADDRESS",
  "POLYMARKET_BUILDER_API_KEY",
  "POLYMARKET_BUILDER_API_SECRET",
  "POLYMARKET_BUILDER_API_PASSPHRASE",
  "POLYGON_RPC_URL",
  "DFLOW_API_BASE_URL",
  "DFLOW_WS_URL",
  "DFLOW_API_KEY",
  "SOLANA_RPC_URL",
  "OPINION_API_KEY",
  "OPINION_BUILDER_API_KEY",
  "OPINION_BSC_RPC_URL",
  "PREDICT_FUN_API_KEY",
  "PREDICT_FUN_BSC_RPC_URL",
  "LIMITLESS_BASE_RPC_URL",
  "LIMITLESS_PARTNER_TOKEN_ID",
  "LIMITLESS_PARTNER_TOKEN_SECRET",
  "LIMITLESS_PARTNER_PRIVY_IDENTITY_TOKEN",
  "SXBET_API_KEY",
  "SXBET_RPC_URL",
  "HYDROMANCER_API_KEY",
  "HYDROMANCER_API_BASE_URL",
  "POLYGON_NATIVE_USD_UPPER_BOUND_MICROS",
  "SOLANA_NATIVE_USD_UPPER_BOUND_MICROS",
  "BSC_NATIVE_USD_UPPER_BOUND_MICROS",
  "BASE_NATIVE_USD_UPPER_BOUND_MICROS",
  "SX_NETWORK_NATIVE_USD_UPPER_BOUND_MICROS",
  "HYDROMANCER_NATIVE_USD_UPPER_BOUND_MICROS",
  "POLYGON_NETWORK_COST_POLICY_VALID_UNTIL",
  "SOLANA_NETWORK_COST_POLICY_VALID_UNTIL",
  "BSC_NETWORK_COST_POLICY_VALID_UNTIL",
  "BASE_NETWORK_COST_POLICY_VALID_UNTIL",
  "SX_NETWORK_COST_POLICY_VALID_UNTIL",
  "HYDROMANCER_NETWORK_COST_POLICY_VALID_UNTIL",
  "CANARY_MAX_TOTAL_MICROS",
  "RESEND_API_KEY",
  "EMAIL_FROM",
  "OPERATOR_EMAILS",
] as const);

type EnvironmentSource = Readonly<Record<string, string | undefined>>;

export function sanitizeTestServerEnvironment(
  source: EnvironmentSource,
): Record<string, string> {
  const blocked = new Set<string>(TEST_SERVER_BLOCKED_ENV_NAMES);
  const sanitized = Object.fromEntries(
    Object.entries(source).filter(
      (entry): entry is [string, string] =>
        entry[1] !== undefined && !blocked.has(entry[0]),
    ),
  );

  for (const name of TEST_SERVER_BLOCKED_ENV_NAMES) {
    sanitized[name] = "";
  }

  // Tests can never inherit live mutation authority from the operator shell.
  sanitized.EXECUTION_MODE = "disabled";
  sanitized.RECOVERY_ACTION_MODE = "frozen";
  return sanitized;
}
